name: PR Preview
author: Ross Williams
description: >
  Deploy a pull request preview to GitHub Pages, similar to Vercel and
  Netlify.

branding:
  icon: git-pull-request
  color: yellow

inputs:
  preview-branch:
    description: >
      Branch on which the previews will be deployed. This should be the
      same branch that your GitHub Pages site is deployed from.
    required: false
    default: gh-pages
  umbrella-dir:
    description: >
      Name of the directory containing all previews. All previews will be
      created inside this directory.

      The umbrella directory is used to namespace previews from your main
      branch's deployment on GitHub Pages.

      Set to `.` to place preview directories into the root directory, but
      be aware that this may cause your main branch's deployment to
      interfere with your preview deployments (and vice-versa!)
    required: false
    default: pr-preview
  source-dir:
    description: >
      Directory containing files to deploy.

      E.g. if your project builds to `./dist/` you would put `dist` here.
      For the root directory, put `.` here (this is the default).

      Equivalent to JamesIves/github-pages-deploy-action 'folder' setting.

      Will be ignored when removing a preview.
    required: false
    default: .
  action:
    description: >
      Determines what this action will do when it is executed. Supported
      values: `deploy`, `remove`, `null`, `auto` (default).

      If set to `deploy`, will attempt to deploy the preview and overwrite
      any existing preview in that location.

      If set to `remove`, will attempt to remove the preview in that
      location.

      If set to `null`, the action will not do anything.

      If set to `auto`, the action will try to determine whether to deploy
      or remove the preview. It will deploy the preview on
      `pull_request.types.synchronize` events, and remove it on
      `pull_request.types.closed` events. It will not do anything for all
      other events. `auto` is the default value.
    required: false
    default: auto

runs:
  using: composite
  steps:
    - name: Store environment variables
      run: |
        echo "action=${{ inputs.action }}" >> $GITHUB_ENV
        echo "emptydir=$(mktemp -d)" >> $GITHUB_ENV

        pagesurl=$(echo $GITHUB_REPOSITORY | sed 's/\//.github.io\//')
        echo "pagesurl=$pagesurl" >> $GITHUB_ENV

        targetdir=${{ inputs.umbrella-dir }}
        targetdir+="/pr-"
        targetdir+=${{ github.event.number }}
        echo "targetdir=$targetdir" >> $GITHUB_ENV
      shell: bash

    - name: Determine auto action
      if: env.action == "auto"
      run: ./lib/determine-auto-action.sh
      shell: bash

    - name: Deploy preview directory
      if: env.action == "deploy"
      uses: JamesIves/github-pages-deploy-action@4
      with:
        branch: ${{ inputs.preview-branch }}
        folder: ${{ inputs.source-dir }}
        target-folder: ${{ env.targetdir }}

    - name: Remove preview directory
      if: env.action == "remove"
      uses: JamesIves/github-pages-deploy-action@4
      with:
        branch: ${{ inputs.preview-branch }}
        folder: ${{ env.emptydir }}
        target-folder: ${{ env.targetdir }}
